### ISSUE TITLE
System Manager

### ISSUE THREAD

**Issue by AndreFerreira5** [AndreFerreira5/iot-system-sim#1]
**Goal:** Initialize and coordinate the overall system

**Description:** Main process that starts up all other components. Reads config file, creates IPC mechanisms, launches worker processes and alert watcher process, creates threads, handles shutdown.

**Tasks:**
    

   - [ ] Read and validate config file
   - [ ]  Create named pipes for SENSOR_PIPE and CONSOLE_PIPE IPC
   - [x] Create worker processes
   - [ ]  Create Alerts Watcher process
   - [ ]  Create Sensor Reader and Console Reader threads
   - [ ]  Create message queue
   - [x]  Create Bin Max Heap data structure
   - [ ]  Create and initialize shared memory
   - [x] Handle SIGINT to shutdown system gracefully
