### ISSUE TITLE
Worker

### ISSUE THREAD

**Issue by AndreFerreira5** [AndreFerreira5/iot-system-sim#5]
**Goal:** Execute tasks related to sensor data and console commands

**Description:** Process that receives tasks from Dispatcher over unnamed pipe and executes them, updating shared memory and sending responses as needed.

**Tasks:**
- [ ] Read task from unnamed pipe
- [ ] Execute sensor data tasks:
    - [ ] Update shared memory with sensor stats
- [ ] Execute console command tasks:
    - [ ] Read/update shared memory
    - [ ] Send response to console process via message queue
- [ ] Update status when done
