### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by AndreFerreira5** [AndreFerreira5/iot-system-sim#9]
**Goal:** Receive and process log requests.

**Description:** Process that receives log requests from other processes, parses them and writes them to the log file.

**Tasks:**

   - [x] Receive log requests
   - [x] Parse the received info
   - [x] Write timestamped parsed log to file
   - [x] Handle SIGINT
